#!/bin/bash



sudo echo am33xx_pwm > /sys/devices/bone_capemgr.9/slots
sudo echo bone_pwm_P8_13 > /sys/devices/bone_capemgr.9/slots
sudo echo BB-UART4 > /sys/devices/bone_capemgr.9/slots
sudo echo BB-UART1 > /sys/devices/bone_capemgr.9/slots
sudo echo BB-ADC > /sys/devices/bone_capemgr.9/slots

more /sys/devices/bone_capemgr.9/slots
