#!/bin/bash



sudo echo am33xx_pwm > /sys/devices/platform/bone_capemgr/slots
sudo echo bone_pwm_P8_13 > /sys/devices/platform/bone_capemgr/slots
sudo sh -c "echo 'BB-UART4' > /sys/devices/platform/bone_capemgr/slots"

more /sys/devices/platform/bone_capemgr/slots
